2020-11-10 19:11:20 [[31merror[39m]: code: 404;
 message: Post not found;
 error-stack: Error: Post not found
    at Object.getAllEntities (/home/max/Work/rs/myApp/server/src/utils/db.ts:17:9)
    at Object.getAll (/home/max/Work/rs/myApp/server/src/resources/users/user.repository.ts:9:21)
    at UserService.getAll (/home/max/Work/rs/myApp/server/src/resources/users/user.service.ts:6:32)
    at _router.get (/home/max/Work/rs/myApp/server/src/resources/users/user.router.ts:24:52)
    at Layer.handle [as handle_request] (/home/max/Work/rs/myApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/myApp/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/max/Work/rs/myApp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/max/Work/rs/myApp/node_modules/express/lib/router/layer.js:95:5)
    at /home/max/Work/rs/myApp/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/max/Work/rs/myApp/node_modules/express/lib/router/index.js:335:12);

2020-11-10 19:11:47 [[31merror[39m]: code: 500;
 message: Internal Server Error;
 error-stack: undefined;

2020-11-10 19:40:45 [[31merror[39m]: [Unhandled Rejection] Error: Oops!
    at App.initializeRouters (/home/max/Work/rs/myApp/server/src/app.ts:29:20)
    at new App (/home/max/Work/rs/myApp/server/src/app.ts:21:10)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:5:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2020-11-11 11:59:10 [[31merror[39m]: code: 404;
 message: Post not found;
 error-stack: Error: Post not found
    at Object.getAllEntities (/home/max/Work/rs/myApp/server/src/utils/db.ts:17:9)
    at Object.getAll (/home/max/Work/rs/myApp/server/src/resources/users/user.repository.ts:9:21)
    at UserService.getAll (/home/max/Work/rs/myApp/server/src/resources/users/user.service.ts:6:32)
    at _router.get.handleErrorAsync_1.default (/home/max/Work/rs/myApp/server/src/resources/users/user.router.ts:23:48)
    at /home/max/Work/rs/myApp/server/src/middleware/handleErrorAsync.ts:4:15
    at Layer.handle [as handle_request] (/home/max/Work/rs/myApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/myApp/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/max/Work/rs/myApp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/max/Work/rs/myApp/node_modules/express/lib/router/layer.js:95:5)
    at /home/max/Work/rs/myApp/node_modules/express/lib/router/index.js:281:22;

2020-11-11 12:00:08 [[31merror[39m]: [Unhandled Rejection] Error: Post not found
    at Object.getAllEntities (/home/max/Work/rs/myApp/server/src/utils/db.ts:17:9)
    at Object.getAll (/home/max/Work/rs/myApp/server/src/resources/users/user.repository.ts:9:21)
    at UserService.getAll (/home/max/Work/rs/myApp/server/src/resources/users/user.service.ts:6:32)
    at _router.get (/home/max/Work/rs/myApp/server/src/resources/users/user.router.ts:23:48)
    at Layer.handle [as handle_request] (/home/max/Work/rs/myApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/myApp/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/max/Work/rs/myApp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/max/Work/rs/myApp/node_modules/express/lib/router/layer.js:95:5)
    at /home/max/Work/rs/myApp/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/max/Work/rs/myApp/node_modules/express/lib/router/index.js:335:12)
2020-11-11 14:03:02 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:03:02 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:03:48 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:03:48 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:04:16 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5001
Error: listen EADDRINUSE: address already in use :::5001
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:04:16 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5001
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:27:21 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:27:21 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:29:20 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:29:20 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:29:55 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:29:55 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:44:41 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:44:41 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:53:16 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:53:16 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:56:21 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:56:21 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 17:38:17 [[31merror[39m]: code: 417;
 message: Users with this username exists;
 error-stack: Error: Users with this username exists
    at Object.save (/home/max/Work/rs/myApp/server/src/resources/users/user.repository.ts:19:19)
    at process._tickCallback (internal/process/next_tick.js:68:7);

