2020-11-10 18:59:23 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:00:57 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:05:27 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:10:32 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:11:05 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:11:20 [[31merror[39m]: code: 404;
 message: Post not found;
 error-stack: Error: Post not found
    at Object.getAllEntities (/home/max/Work/rs/myApp/server/src/utils/db.ts:17:9)
    at Object.getAll (/home/max/Work/rs/myApp/server/src/resources/users/user.repository.ts:9:21)
    at UserService.getAll (/home/max/Work/rs/myApp/server/src/resources/users/user.service.ts:6:32)
    at _router.get (/home/max/Work/rs/myApp/server/src/resources/users/user.router.ts:24:52)
    at Layer.handle [as handle_request] (/home/max/Work/rs/myApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/myApp/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/max/Work/rs/myApp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/max/Work/rs/myApp/node_modules/express/lib/router/layer.js:95:5)
    at /home/max/Work/rs/myApp/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/max/Work/rs/myApp/node_modules/express/lib/router/index.js:335:12);

2020-11-10 19:11:46 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:11:47 [[31merror[39m]: code: 500;
 message: Internal Server Error;
 error-stack: undefined;

2020-11-10 19:12:04 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:21:26 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:23:29 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:24:14 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:24:40 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:25:18 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:40:21 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:40:45 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:40:45 [[31merror[39m]: [Unhandled Rejection] Error: Oops!
    at App.initializeRouters (/home/max/Work/rs/myApp/server/src/app.ts:29:20)
    at new App (/home/max/Work/rs/myApp/server/src/app.ts:21:10)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:5:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2020-11-10 19:41:11 [[32minfo[39m]: > App listening on port 5000
2020-11-10 19:45:45 [[32minfo[39m]: > App listening on port 5000
2020-11-11 10:51:33 [[32minfo[39m]: > App listening on port 5000
2020-11-11 11:12:10 [[32minfo[39m]:  App listening on port 5000
2020-11-11 11:13:51 [[32minfo[39m]:  App listening on port 5000
2020-11-11 11:32:30 [[32minfo[39m]:  App listening on port 5000
2020-11-11 11:37:32 [[32minfo[39m]:  App listening on port 5000
2020-11-11 11:39:19 [[32minfo[39m]:  App listening on port 5000
2020-11-11 11:44:07 [[32minfo[39m]:  App listening on port 5000
2020-11-11 11:57:03 [[32minfo[39m]:  App listening on port 5000
2020-11-11 11:57:13 [[32minfo[39m]:  App listening on port 5000
2020-11-11 11:57:34 [[32minfo[39m]:  App listening on port 5000
2020-11-11 11:58:27 [[32minfo[39m]:  App listening on port 5000
2020-11-11 11:58:40 [[32minfo[39m]:  App listening on port 5000
2020-11-11 11:59:03 [[32minfo[39m]:  App listening on port 5000
2020-11-11 11:59:10 [[31merror[39m]: code: 404;
 message: Post not found;
 error-stack: Error: Post not found
    at Object.getAllEntities (/home/max/Work/rs/myApp/server/src/utils/db.ts:17:9)
    at Object.getAll (/home/max/Work/rs/myApp/server/src/resources/users/user.repository.ts:9:21)
    at UserService.getAll (/home/max/Work/rs/myApp/server/src/resources/users/user.service.ts:6:32)
    at _router.get.handleErrorAsync_1.default (/home/max/Work/rs/myApp/server/src/resources/users/user.router.ts:23:48)
    at /home/max/Work/rs/myApp/server/src/middleware/handleErrorAsync.ts:4:15
    at Layer.handle [as handle_request] (/home/max/Work/rs/myApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/myApp/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/max/Work/rs/myApp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/max/Work/rs/myApp/node_modules/express/lib/router/layer.js:95:5)
    at /home/max/Work/rs/myApp/node_modules/express/lib/router/index.js:281:22;

2020-11-11 12:00:05 [[32minfo[39m]:  App listening on port 5000
2020-11-11 12:00:08 [[31merror[39m]: [Unhandled Rejection] Error: Post not found
    at Object.getAllEntities (/home/max/Work/rs/myApp/server/src/utils/db.ts:17:9)
    at Object.getAll (/home/max/Work/rs/myApp/server/src/resources/users/user.repository.ts:9:21)
    at UserService.getAll (/home/max/Work/rs/myApp/server/src/resources/users/user.service.ts:6:32)
    at _router.get (/home/max/Work/rs/myApp/server/src/resources/users/user.router.ts:23:48)
    at Layer.handle [as handle_request] (/home/max/Work/rs/myApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/max/Work/rs/myApp/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/max/Work/rs/myApp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/max/Work/rs/myApp/node_modules/express/lib/router/layer.js:95:5)
    at /home/max/Work/rs/myApp/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/max/Work/rs/myApp/node_modules/express/lib/router/index.js:335:12)
2020-11-11 12:06:20 [[32minfo[39m]:  App listening on port 5000
2020-11-11 12:06:44 [[32minfo[39m]:  App listening on port 5000
2020-11-11 12:08:00 [[32minfo[39m]:  App listening on port 5000
2020-11-11 12:35:17 [[32minfo[39m]:  App listening on port 5000
2020-11-11 12:46:24 [[32minfo[39m]:  App listening on port 5000
2020-11-11 12:47:57 [[32minfo[39m]:  App listening on port 5000
2020-11-11 12:51:01 [[32minfo[39m]:  App listening on port 5000
2020-11-11 12:52:08 [[32minfo[39m]:  App listening on port 5000
2020-11-11 13:15:46 [[32minfo[39m]:  App listening on port 5000
2020-11-11 13:20:02 [[32minfo[39m]:  App listening on port 5000
2020-11-11 13:20:32 [[32minfo[39m]:  App listening on port 5000
2020-11-11 13:43:30 [[32minfo[39m]:  App listening on port 5000
2020-11-11 13:59:39 [[32minfo[39m]:  App listening on port 5000
2020-11-11 14:03:00 [[32minfo[39m]:  App listening on port 5000
2020-11-11 14:03:02 [[32minfo[39m]: Successfully connect to DB
2020-11-11 14:03:02 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:03:02 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:03:47 [[32minfo[39m]:  App listening on port 5000
2020-11-11 14:03:48 [[32minfo[39m]: Successfully connect to DB
2020-11-11 14:03:48 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:03:48 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:04:14 [[32minfo[39m]:  App listening on port 5001
2020-11-11 14:04:16 [[32minfo[39m]: Successfully connect to DB
2020-11-11 14:04:16 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5001
Error: listen EADDRINUSE: address already in use :::5001
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:04:16 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5001
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:27:20 [[32minfo[39m]:  App listening on port 5000
2020-11-11 14:27:21 [[32minfo[39m]: Successfully connect to DB
2020-11-11 14:27:21 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:27:21 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:29:19 [[32minfo[39m]:  App listening on port 5000
2020-11-11 14:29:20 [[32minfo[39m]: Successfully connect to DB
2020-11-11 14:29:20 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:29:20 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:29:54 [[32minfo[39m]:  App listening on port 5000
2020-11-11 14:29:55 [[32minfo[39m]: Successfully connect to DB
2020-11-11 14:29:55 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:29:55 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:44:40 [[32minfo[39m]:  App listening on port 5000
2020-11-11 14:44:41 [[32minfo[39m]: Successfully connect to DB
2020-11-11 14:44:41 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:44:41 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:53:15 [[32minfo[39m]:  App listening on port 5000
2020-11-11 14:53:16 [[32minfo[39m]: Successfully connect to DB
2020-11-11 14:53:16 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:53:16 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:56:20 [[32minfo[39m]:  App listening on port 5000
2020-11-11 14:56:21 [[32minfo[39m]: Successfully connect to DB
2020-11-11 14:56:21 [[31merror[39m]: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:56:21 [[31merror[39m]: [Unhandled Exception] Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/max/Work/rs/myApp/node_modules/express/lib/application.js:618:24)
    at App.listen (/home/max/Work/rs/myApp/server/src/app.ts:36:14)
    at NativeConnection.db.on.once (/home/max/Work/rs/myApp/server/src/server.ts:18:13)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.EventEmitter.emit (domain.js:448:20)
    at _setClient (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:972:8)
    at client.connect (/home/max/Work/rs/myApp/node_modules/mongoose/lib/connection.js:815:7)
    at /home/max/Work/rs/myApp/node_modules/mongodb/lib/utils.js:677:5
    at err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/mongo_client.js:226:7)
    at connectCallback (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:366:5)
    at topology.connect.err (/home/max/Work/rs/myApp/node_modules/mongodb/lib/operations/connect.js:602:5)
    at connectHandler (/home/max/Work/rs/myApp/node_modules/mongodb/lib/core/sdam/topology.js:297:43)
2020-11-11 14:56:51 [[32minfo[39m]: Successfully connect to DB
2020-11-11 14:56:51 [[32minfo[39m]:  App listening on port 5000
2020-11-11 15:50:02 [[32minfo[39m]: Successfully connect to DB
2020-11-11 15:50:02 [[32minfo[39m]:  App listening on port 5000
2020-11-11 16:26:14 [[32minfo[39m]: Successfully connect to DB
2020-11-11 16:26:14 [[32minfo[39m]:  App listening on port 5000
2020-11-11 16:27:13 [[32minfo[39m]: Successfully connect to DB
2020-11-11 16:27:13 [[32minfo[39m]:  App listening on port 5000
2020-11-11 17:38:17 [[31merror[39m]: code: 417;
 message: Users with this username exists;
 error-stack: Error: Users with this username exists
    at Object.save (/home/max/Work/rs/myApp/server/src/resources/users/user.repository.ts:19:19)
    at process._tickCallback (internal/process/next_tick.js:68:7);

2020-11-11 17:51:50 [[32minfo[39m]: Successfully connect to DB
2020-11-11 17:51:50 [[32minfo[39m]:  App listening on port 5000
2020-11-11 18:12:30 [[32minfo[39m]: Successfully connect to DB
2020-11-11 18:12:30 [[32minfo[39m]:  App listening on port 5000
2020-11-12 12:47:13 [[31merror[39m]: uncaughtException: Mongoose.connect is not a function
TypeError: Mongoose.connect is not a function
    at Object.exports.connect (/home/max/Work/rs/myApp/server/src/database/database.ts:13:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at main (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:225:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:512:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-11-12 12:47:58 [[31merror[39m]: uncaughtException: Mongoose.connect is not a function
TypeError: Mongoose.connect is not a function
    at Object.exports.connect (/home/max/Work/rs/myApp/server/src/database/database.ts:13:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at main (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:225:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:512:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-11-12 12:49:35 [[31merror[39m]: uncaughtException: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m10[0m:[93m9[0m - [91merror[0m[90m TS7030: [0mNot all code paths return a value.

[7m10[0m         return;
[7m  [0m [91m        ~~~~~~~[0m

TSError: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m10[0m:[93m9[0m - [91merror[0m[90m TS7030: [0mNot all code paths return a value.

[7m10[0m         return;
[7m  [0m [91m        ~~~~~~~[0m

    at createTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-11-12 12:49:40 [[31merror[39m]: uncaughtException: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m10[0m:[93m9[0m - [91merror[0m[90m TS7030: [0mNot all code paths return a value.

[7m10[0m         return;
[7m  [0m [91m        ~~~~~~~[0m

TSError: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m10[0m:[93m9[0m - [91merror[0m[90m TS7030: [0mNot all code paths return a value.

[7m10[0m         return;
[7m  [0m [91m        ~~~~~~~[0m

    at createTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-11-12 12:49:54 [[31merror[39m]: uncaughtException: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m10[0m:[93m9[0m - [91merror[0m[90m TS7030: [0mNot all code paths return a value.

[7m10[0m         return;
[7m  [0m [91m        ~~~~~~~[0m

TSError: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m10[0m:[93m9[0m - [91merror[0m[90m TS7030: [0mNot all code paths return a value.

[7m10[0m         return;
[7m  [0m [91m        ~~~~~~~[0m

    at createTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-11-12 12:50:08 [[31merror[39m]: uncaughtException: Mongoose.connect is not a function
TypeError: Mongoose.connect is not a function
    at Object.exports.connect (/home/max/Work/rs/myApp/server/src/database/database.ts:13:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at main (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:225:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:512:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-11-12 12:51:14 [[31merror[39m]: uncaughtException: Mongoose.connect is not a function
TypeError: Mongoose.connect is not a function
    at Object.exports.connect (/home/max/Work/rs/myApp/server/src/server.ts:15:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:37:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at main (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:225:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:512:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-11-12 12:51:52 [[31merror[39m]: uncaughtException: Mongoose.connect is not a function
TypeError: Mongoose.connect is not a function
    at Object.exports.connect (/home/max/Work/rs/myApp/server/src/database/database.ts:13:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at main (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:225:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:512:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-11-12 12:53:06 [[31merror[39m]: uncaughtException: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m2[0m:[93m1[0m - [91merror[0m[90m TS6133: [0m'config' is declared but its value is never read.

[7m2[0m import config from '../common/config'
[7m [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m

TSError: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m2[0m:[93m1[0m - [91merror[0m[90m TS6133: [0m'config' is declared but its value is never read.

[7m2[0m import config from '../common/config'
[7m [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m

    at createTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-11-12 12:53:15 [[31merror[39m]: uncaughtException: Cannot read property 'once' of undefined
TypeError: Cannot read property 'once' of undefined
    at Object.exports.connect (/home/max/Work/rs/myApp/server/src/database/database.ts:22:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at main (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:225:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:512:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-11-12 12:54:53 [[31merror[39m]: uncaughtException: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m41[0m:[93m1[0m - [91merror[0m[90m TS7027: [0mUnreachable code detected.

[7m 41[0m export const disconnect = () => {
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[7m 42[0m     if (!database) {
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~[0m
[7m...[0m 
[7m 46[0m     Mongoose.disconnect();
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[7m 47[0m };
[7m   [0m [91m~~[0m
[96mserver/src/database/database.ts[0m:[93m4[0m:[93m1[0m - [91merror[0m[90m TS6133: [0m'UserModel' is declared but its value is never read.

[7m4[0m import { UserModel } from './users/users.model';
[7m [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[96mserver/src/database/database.ts[0m:[93m8[0m:[93m24[0m - [91merror[0m[90m TS7030: [0mNot all code paths return a value.

[7m8[0m export const connect = () => {
[7m [0m [91m                       ~~~~~~~[0m
[96mserver/src/database/database.ts[0m:[93m33[0m:[93m63[0m - [91merror[0m[90m TS2304: [0mCannot find name 'PORT'.

[7m33[0m             logger.info(`App is running on http://localhost:${PORT}`)
[7m  [0m [91m                                                              ~~~~[0m
[96mserver/src/database/database.ts[0m:[93m34[0m:[93m11[0m - [91merror[0m[90m TS1128: [0mDeclaration or statement expected.

[7m34[0m           );
[7m  [0m [91m          ~[0m
[96mserver/src/database/database.ts[0m:[93m40[0m:[93m1[0m - [91merror[0m[90m TS1128: [0mDeclaration or statement expected.

[7m40[0m };
[7m  [0m [91m~[0m

TSError: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m41[0m:[93m1[0m - [91merror[0m[90m TS7027: [0mUnreachable code detected.

[7m 41[0m export const disconnect = () => {
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[7m 42[0m     if (!database) {
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~[0m
[7m...[0m 
[7m 46[0m     Mongoose.disconnect();
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[7m 47[0m };
[7m   [0m [91m~~[0m
[96mserver/src/database/database.ts[0m:[93m4[0m:[93m1[0m - [91merror[0m[90m TS6133: [0m'UserModel' is declared but its value is never read.

[7m4[0m import { UserModel } from './users/users.model';
[7m [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[96mserver/src/database/database.ts[0m:[93m8[0m:[93m24[0m - [91merror[0m[90m TS7030: [0mNot all code paths return a value.

[7m8[0m export const connect = () => {
[7m [0m [91m                       ~~~~~~~[0m
[96mserver/src/database/database.ts[0m:[93m33[0m:[93m63[0m - [91merror[0m[90m TS2304: [0mCannot find name 'PORT'.

[7m33[0m             logger.info(`App is running on http://localhost:${PORT}`)
[7m  [0m [91m                                                              ~~~~[0m
[96mserver/src/database/database.ts[0m:[93m34[0m:[93m11[0m - [91merror[0m[90m TS1128: [0mDeclaration or statement expected.

[7m34[0m           );
[7m  [0m [91m          ~[0m
[96mserver/src/database/database.ts[0m:[93m40[0m:[93m1[0m - [91merror[0m[90m TS1128: [0mDeclaration or statement expected.

[7m40[0m };
[7m  [0m [91m~[0m

    at createTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-11-12 12:55:06 [[31merror[39m]: uncaughtException: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m41[0m:[93m1[0m - [91merror[0m[90m TS7027: [0mUnreachable code detected.

[7m 41[0m export const disconnect = () => {
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[7m 42[0m     if (!database) {
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~[0m
[7m...[0m 
[7m 46[0m     Mongoose.disconnect();
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[7m 47[0m };
[7m   [0m [91m~~[0m
[96mserver/src/database/database.ts[0m:[93m4[0m:[93m1[0m - [91merror[0m[90m TS6133: [0m'UserModel' is declared but its value is never read.

[7m4[0m import { UserModel } from './users/users.model';
[7m [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[96mserver/src/database/database.ts[0m:[93m8[0m:[93m24[0m - [91merror[0m[90m TS7030: [0mNot all code paths return a value.

[7m8[0m export const connect = () => {
[7m [0m [91m                       ~~~~~~~[0m
[96mserver/src/database/database.ts[0m:[93m33[0m:[93m63[0m - [91merror[0m[90m TS2304: [0mCannot find name 'PORT'.

[7m33[0m             logger.info(`App is running on http://localhost:${PORT}`)
[7m  [0m [91m                                                              ~~~~[0m
[96mserver/src/database/database.ts[0m:[93m34[0m:[93m11[0m - [91merror[0m[90m TS1128: [0mDeclaration or statement expected.

[7m34[0m           );
[7m  [0m [91m          ~[0m
[96mserver/src/database/database.ts[0m:[93m35[0m:[93m2[0m - [91merror[0m[90m TS1005: [0m',' expected.

[7m35[0m })
[7m  [0m [91m ~[0m
[96mserver/src/database/database.ts[0m:[93m40[0m:[93m1[0m - [91merror[0m[90m TS1128: [0mDeclaration or statement expected.

[7m40[0m };
[7m  [0m [91m~[0m

TSError: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m41[0m:[93m1[0m - [91merror[0m[90m TS7027: [0mUnreachable code detected.

[7m 41[0m export const disconnect = () => {
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[7m 42[0m     if (!database) {
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~[0m
[7m...[0m 
[7m 46[0m     Mongoose.disconnect();
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[7m 47[0m };
[7m   [0m [91m~~[0m
[96mserver/src/database/database.ts[0m:[93m4[0m:[93m1[0m - [91merror[0m[90m TS6133: [0m'UserModel' is declared but its value is never read.

[7m4[0m import { UserModel } from './users/users.model';
[7m [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[96mserver/src/database/database.ts[0m:[93m8[0m:[93m24[0m - [91merror[0m[90m TS7030: [0mNot all code paths return a value.

[7m8[0m export const connect = () => {
[7m [0m [91m                       ~~~~~~~[0m
[96mserver/src/database/database.ts[0m:[93m33[0m:[93m63[0m - [91merror[0m[90m TS2304: [0mCannot find name 'PORT'.

[7m33[0m             logger.info(`App is running on http://localhost:${PORT}`)
[7m  [0m [91m                                                              ~~~~[0m
[96mserver/src/database/database.ts[0m:[93m34[0m:[93m11[0m - [91merror[0m[90m TS1128: [0mDeclaration or statement expected.

[7m34[0m           );
[7m  [0m [91m          ~[0m
[96mserver/src/database/database.ts[0m:[93m35[0m:[93m2[0m - [91merror[0m[90m TS1005: [0m',' expected.

[7m35[0m })
[7m  [0m [91m ~[0m
[96mserver/src/database/database.ts[0m:[93m40[0m:[93m1[0m - [91merror[0m[90m TS1128: [0mDeclaration or statement expected.

[7m40[0m };
[7m  [0m [91m~[0m

    at createTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-11-12 12:55:24 [[31merror[39m]: uncaughtException: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m29[0m:[93m5[0m - [91merror[0m[90m TS2304: [0mCannot find name 'db'.

[7m29[0m     db.on('error', () => logger.error('MongoDB connection error:')).once(
[7m  [0m [91m    ~~[0m
[96mserver/src/database/database.ts[0m:[93m33[0m:[93m13[0m - [91merror[0m[90m TS2304: [0mCannot find name 'app'.

[7m33[0m             app.listen(PORT, () =>
[7m  [0m [91m            ~~~[0m
[96mserver/src/database/database.ts[0m:[93m33[0m:[93m24[0m - [91merror[0m[90m TS2304: [0mCannot find name 'PORT'.

[7m33[0m             app.listen(PORT, () =>
[7m  [0m [91m                       ~~~~[0m
[96mserver/src/database/database.ts[0m:[93m34[0m:[93m67[0m - [91merror[0m[90m TS2304: [0mCannot find name 'PORT'.

[7m34[0m                 logger.info(`App is running on http://localhost:${PORT}`)
[7m  [0m [91m                                                                  ~~~~[0m

TSError: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m29[0m:[93m5[0m - [91merror[0m[90m TS2304: [0mCannot find name 'db'.

[7m29[0m     db.on('error', () => logger.error('MongoDB connection error:')).once(
[7m  [0m [91m    ~~[0m
[96mserver/src/database/database.ts[0m:[93m33[0m:[93m13[0m - [91merror[0m[90m TS2304: [0mCannot find name 'app'.

[7m33[0m             app.listen(PORT, () =>
[7m  [0m [91m            ~~~[0m
[96mserver/src/database/database.ts[0m:[93m33[0m:[93m24[0m - [91merror[0m[90m TS2304: [0mCannot find name 'PORT'.

[7m33[0m             app.listen(PORT, () =>
[7m  [0m [91m                       ~~~~[0m
[96mserver/src/database/database.ts[0m:[93m34[0m:[93m67[0m - [91merror[0m[90m TS2304: [0mCannot find name 'PORT'.

[7m34[0m                 logger.info(`App is running on http://localhost:${PORT}`)
[7m  [0m [91m                                                                  ~~~~[0m

    at createTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-11-12 12:55:37 [[31merror[39m]: uncaughtException: Cannot read property 'on' of undefined
TypeError: Cannot read property 'on' of undefined
    at Object.exports.connect (/home/max/Work/rs/myApp/server/src/database/database.ts:29:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at main (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:225:14)
    at Object.<anonymous> (/home/max/Work/rs/myApp/node_modules/ts-node/src/bin.ts:512:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-11-12 12:56:05 [[32minfo[39m]:  App listening on port 5000
2020-11-12 12:56:20 [[31merror[39m]: uncaughtException: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m13[0m:[93m22[0m - [91merror[0m[90m TS2304: [0mCannot find name 'config'.

[7m13[0m     Mongoose.connect(config.MONGO_CONNECTION_STRING, {
[7m  [0m [91m                     ~~~~~~[0m

TSError: ⨯ Unable to compile TypeScript:
[96mserver/src/database/database.ts[0m:[93m13[0m:[93m22[0m - [91merror[0m[90m TS2304: [0mCannot find name 'config'.

[7m13[0m     Mongoose.connect(config.MONGO_CONNECTION_STRING, {
[7m  [0m [91m                     ~~~~~~[0m

    at createTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/max/Work/rs/myApp/server/src/server.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/max/Work/rs/myApp/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-11-12 12:56:29 [[32minfo[39m]:  App listening on port 5000
2020-11-12 12:56:30 [[32minfo[39m]: Successfully connect to DB
2020-11-12 12:56:40 [[32minfo[39m]:  App listening on port 5000
2020-11-12 12:56:41 [[32minfo[39m]: Successfully connect to DB
2020-11-12 12:56:48 [[32minfo[39m]:  App listening on port 5000
2020-11-12 12:56:49 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:04:40 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:04:41 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:07:51 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:07:52 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:08:41 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:08:42 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:08:47 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:08:48 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:12:37 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:12:38 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:12:59 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:13:00 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:13:35 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:13:36 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:13:50 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:13:51 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:14:57 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:14:58 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:18:03 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:18:04 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:18:29 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:18:30 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:25:07 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:25:08 [[32minfo[39m]: Successfully connect to DB
2020-11-12 13:25:22 [[32minfo[39m]:  App listening on port 5000
2020-11-12 13:25:23 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:08:13 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:08:14 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:10:38 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:10:39 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:32:33 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:32:34 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:32:53 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:32:54 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:34:05 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:34:06 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:41:45 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:41:46 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:42:31 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:42:32 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:42:44 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:42:45 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:43:22 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:43:23 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:43:35 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:43:36 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:44:30 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:44:31 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:45:34 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:45:35 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:46:14 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:46:15 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:57:04 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:57:05 [[32minfo[39m]: Successfully connect to DB
2020-11-12 14:57:11 [[32minfo[39m]:  App listening on port 5000
2020-11-12 14:57:12 [[32minfo[39m]: Successfully connect to DB
2020-11-12 15:00:26 [[32minfo[39m]:  App listening on port 5000
2020-11-12 15:00:27 [[32minfo[39m]: Successfully connect to DB
2020-11-12 15:00:49 [[32minfo[39m]:  App listening on port 5000
2020-11-12 15:00:50 [[32minfo[39m]: Successfully connect to DB
2020-11-12 15:17:44 [[32minfo[39m]:  App listening on port 5000
2020-11-12 15:17:46 [[32minfo[39m]: Successfully connect to DB
2020-11-12 15:18:15 [[32minfo[39m]:  App listening on port 5000
2020-11-12 15:18:16 [[32minfo[39m]: Successfully connect to DB
2020-11-12 15:25:42 [[32minfo[39m]:  App listening on port 5000
2020-11-12 15:25:43 [[32minfo[39m]: Successfully connect to DB
2020-11-12 15:26:37 [[32minfo[39m]:  App listening on port 5000
2020-11-12 15:26:38 [[32minfo[39m]: Successfully connect to DB
2020-11-12 15:28:41 [[32minfo[39m]:  App listening on port 5000
2020-11-12 15:28:42 [[32minfo[39m]: Successfully connect to DB
2020-11-12 15:31:29 [[32minfo[39m]:  App listening on port 5000
2020-11-12 15:31:30 [[32minfo[39m]: Successfully connect to DB
